stages:
  - test

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_REGISTRY_GET: "dockerregistry.americas.phoenixcontact.com"
  DOCKER_IMAGE_MOCHA: dockerregistry.americas.phoenixcontact.com/ima-ism/psf/docker/pxc-mocha:latest
 # DOCKER_IMAGE_NODE: dockerregistry.americas.phoenixcontact.com/node:11.13.0-alpine
  GIT_SUBMODULE_STRATEGY: none


test:
  stage: test
  tags:
    - docker
  image: dockerregistry.americas.phoenixcontact.com/application-hosting/pxc-us-docker:18.06
  services:
    - name: docker:dind
      command: ["--insecure-registry=dockerregistry.americas.phoenixcontact.com"]
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $DOCKER_REGISTRY_GET
    - docker pull $DOCKER_IMAGE_MOCHA
    - docker run --rm -i -v $CI_PROJECT_DIR:/mocha $DOCKER_IMAGE_MOCHA sh -c "npm install && npm test"
    - docker logout $DOCKER_REGISTRY_GET
#  only:
#    - master
