language: node_js
node_js:
  - "stable"
cache:
  directories:
  - "node_modules"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run test
  - istanbul cover ./node_modules/bin/_mocha --reporter lcovonly -- -R spec
after_success:
    - codecov